# not used
{
  "zero_optimization": {
      "stage": 3,
      "reduce_bucket_size": 50000000,
      "contiguous_gradients": true,
      "overlap_comm": true,
      "reduce_scatter": true,
      "reduce_bucket_size": 500000000,
      "allgather_bucket_size": 500000000,
      "offload_optimizer": { # 없으면 OOM
        "device": "cpu"
      },
      "stage3_max_live_parameters": 1000000000,
      "stage3_max_reuse_distance": 1000000000,
      "stage3_prefetch_bucket_size": 500000000,
      "stage3_param_persistence_threshold": 1000000,
  },

  "optimizer": {
    "type": "cpu_adam",
    # "type": "adam",
    "params": {
      "lr": 0.0002,
      "betas": [0.9, 0.95],
      "eps":  1.0e-8,
    }
  },
}