# not used
{
  "zero_optimization": {
      "stage": 2,
      "contiguous_gradients": true,
      "overlap_comm": true,
      "reduce_scatter": true,
      "reduce_bucket_size": 500000000,
      "allgather_bucket_size": 1000000000,
      "offload_optimizer": { # 없으면 OOM
        "device": "cpu",
        "pin_memory": False, # boost throughput at the cost of extra memory overhead
      },
      "round_robin_gradients": True, # True면 뭐가 좋아지나? stage1&2 optimization
  },

  "optimizer": {
    "type": "cpu_adam",
    # "type": "adam",
    "params": {
      "lr": 0.0002,
      "betas": [0.9, 0.95],
      "eps":  1.0e-8,
    }
  },
}