# Parameters used for text generation
# Make sure `load` is specified somewhere else
{
  # Text gen type: `input-file`, `unconditional` or `interactive`
  "text_gen_type": "input-file",
  # "text_gen_type": "unconditional",

  # Params for all
  "maximum_tokens": 102,
  "prompt_end": "\n",
  "temperature": 0.6,
  "top_p": 0.92,
  "top_k": 50,
  "recompute": false,

  # `unconditional`: samples
  "num_samples": 5,

  # input/output file
  "sample_input_file": "data/inference/sample_input.txt",
  "sample_output_file": "data/inference/300_output.txt",
}
